### ISSUE TITLE
No make install target

### ISSUE THREAD

**Issue by jeena** [socec/moxanix#1]
After building the binary I wanted to do `make install` to install it in my system but ther wasn't any.

I would put the binary and the controllscript into /usr/local/bin (with the pollibility to set the prefix to /usr instead) and the config file into /etc

**Comment by socec** [comment]
After [this commit](https://github.com/socec/moxanix/commit/cded0313c28b57de02d43cb5b67ec6cc24ef8fbf) it is possible to run `make install`. The README file also explains how to change the installation root and the prefix for executables.
