### ISSUE TITLE
Rename moxanix.sh to moxanixctl

### ISSUE THREAD

**Issue by jeena** [socec/moxanix#2]
It's a bit weird that the controlscript is called as the daemon but with a .sh postfix, it should be called something like moxanixctl to make it clear that this is the cortrolscript like you have it in systemdctl and journalctl, etc.

**Comment by socec** [comment]
After [this commit](https://github.com/socec/moxanix/commit/cded0313c28b57de02d43cb5b67ec6cc24ef8fbf) all the installed parts have a base name "moxerver" and the control script was renamed to "moxerverctl".
