### ISSUE TITLE
Add example systemd service file and a System V init script

### ISSUE THREAD

**Issue by jeena** [socec/moxanix#3]
It would be nice if you would offer those startup scripts so I can start moxanix on boot.

**Comment by socec** [comment]
Good suggestion, here is a proposal for systemd service file:

[Unit]
Description=Moxanix - A serial device server, provides console access to multiple serial devices through telnet connection

[Service]
Type=oneshot
WorkingDirectory=/home/user/moxanix
ExecStart=/usr/bin/moxerverctl start 0
ExecStop=/usr/bin moxerverctl stop 0
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

**Comment by jeena** [comment]
Why do you need the WorkingDirectory?

**Comment by socec** [comment]
WorkingDirectory is actually not needed.
The rest is, especially "RemainAfterExit" that makes sure the service children (moxervers) are not killed when the service call exits.

**Comment by jeena** [comment]
I experimented a litle bit more with it and I think forking is the better Type= for it, so my moxanix.service looks like this now:

```
[Unit]
Description=Moxanix - A serial device server, provides console access to multiple serial devices through telnet connection

[Service]
Type=forking
ExecStart=/usr/bin/moxerverctl start 0
ExecStop=/usr/bin/moxerverctl stop 0

[Install]
WantedBy=multi-user.target
```

**Comment by socec** [comment]
Great input!

[This commit](https://github.com/socec/moxanix/commit/7dd6c2dcfb458107c8bf10b001559b22402468a2) adds the systemd service.

I will not be dealing with SystemV now since I don't use it, but contributions are welcome in the future!
